/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Insert.java
 *
 * Created on 21 Jun 12, 9:27:59
 */
package ContohProjectGUI;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ayu
 */
public class Insert extends javax.swing.JFrame {
    /**
     * Creates new form Insert
     */
    public Insert() 
    {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jTextField2.setText(generateCode());
    }
public String generateCode()
{ 
    Statement st;
    ResultSet rs;
    String No_Induk = "";
    Connection con = null;
    String kode = "";   
    int newCode=0;
    try 
    {
        con = koneksi.getConnection();
        String view = "select Top 1 No_Induk from Data_Siswa order by No_Induk desc";
        st = con.createStatement();
        rs = st.executeQuery(view);        
        while (rs.next()) 
        {              
            No_Induk = rs.getString("No_Induk") ;       
        }            
    } 
    catch (Exception ex) 
    {
        JOptionPane.showMessageDialog(null, ex.getMessage().toString());
    }
    if (No_Induk.equals(""))
    {
        kode = "M001";
    }
    else
    {
        kode = No_Induk.substring(1, 4);
        newCode = Integer.parseInt(kode);
        if(newCode < 9)
        {
            newCode = newCode + 1;
            kode = "M00" + newCode;
        }
        else if(newCode < 99)
        {
            newCode = newCode + 1;
            kode = "M0" + newCode;
        }
        else 
        {
            newCode = newCode + 1;
            kode = "M" + newCode;
        } 
    }  
    return kode;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Hobi");

        jLabel5.setText("Jurusan");

        jLabel6.setText("Asal Sekolah");

        jTextField1.setColumns(25);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jRadioButton1.setText("Laki-laki");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Perempuan");

        jCheckBox1.setText("Hobi 1");

        jCheckBox2.setText("Hobi 2");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "SMU", "SMK", "Aliyah"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("No Induk");

        jTextField2.setColumns(8);

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cari Alamat");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IPA", "IPS", "BAHASA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox2))
                                .addComponent(jScrollPane1)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2)
                        .addGap(48, 48, 48)
                        .addComponent(jButton3)
                        .addGap(59, 59, 59)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(281, 338, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PreparedStatement stat;      
        String jenis_kelamin = "";
        String hobi = "";
        Connection con = null;
        try {
            con = koneksi.getConnection();
            String SqlInsert = "insert Data_Siswa values (?,?,?,?,?,?,?)";
            stat = con.prepareStatement(SqlInsert);
            String No_Induk = jTextField2.getText();
            String Nama = jTextField1.getText();
            String Alamat = jTextArea1.getText();
            if (jRadioButton1.isSelected()) 
            {
                jenis_kelamin = "Laki-laki";
            }
            if (jRadioButton2.isSelected()) 
            {
                jenis_kelamin = "Perempuan";
            }
            if (jCheckBox1.isSelected()) 
            {
                hobi = jCheckBox1.getText();
            }
            if (jCheckBox2.isSelected()) 
            {
                hobi = jCheckBox2.getText();
            }
            if (jCheckBox2.isSelected() && jCheckBox1.isSelected()) 
            {
                hobi = jCheckBox1.getText() + " " + jCheckBox2.getText();
            }
            String jurusan = jComboBox1.getSelectedItem().toString();
            String Asal_Sekolah = jList1.getSelectedValue().toString();
            stat.setString(1, No_Induk);
            stat.setString(2, Nama);
            stat.setString(3, Alamat);
            stat.setString(4, jenis_kelamin);
            stat.setString(5, hobi);
            stat.setString(6, jurusan);
            stat.setString(7, Asal_Sekolah);
            int i = stat.executeUpdate();
            if (i != 0) 
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }        
        jTextField2.setText(generateCode());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement stat;
        ResultSet rs;
        String jenis_kelamin = "";
        String hobi;
        Connection con = null;
        try 
        {
            con = koneksi.getConnection();
            String SqlCari = "Select * from Data_Siswa where No_Induk=?";
            stat = con.prepareStatement(SqlCari);
            String No_Induk = jTextField2.getText();
            stat.setString(1, No_Induk);
            rs = stat.executeQuery();
            rs.next();
            jTextField1.setText(rs.getString("Nama").trim());
            jTextArea1.setText(rs.getString("Alamat").trim());
            jenis_kelamin = rs.getString("Jenis_Kelamin").trim();
            hobi = rs.getString("hobi").trim();
            if (jenis_kelamin.equals("Laki-laki")) 
            {
                jRadioButton1.setSelected(true);
            }
            if (jenis_kelamin.equals("Perempuan")) 
            {
                jRadioButton2.setSelected(true);
            }
            if (hobi.equals("Hobi 1")) 
            {
                jCheckBox1.setSelected(true);
            }
            if (hobi.equals("Hobi 2")) 
            {
                jCheckBox2.setSelected(true);
            }
            if (hobi.equals("Hobi 1 Hobi 2")) 
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
            }
            String Jurusan = rs.getString("Jurusan").trim();
            String Asal_Sekolah = rs.getString("Asal_Sekolah").trim();
            if (Jurusan.equals("IPA")) 
            {
                jComboBox1.setSelectedIndex(0);
            } 
            else if (Jurusan.equals("IPS")) 
            {
                jComboBox1.setSelectedIndex(1);
            } 
            else 
            {
                jComboBox1.setSelectedIndex(2);
            }
            if (Asal_Sekolah.equals("SMU")) 
            {
                jList1.setSelectedIndex(0);
            } 
            else if (Asal_Sekolah.equals("SMK")) 
            {
                jList1.setSelectedIndex(1);
            } 
            else 
            {
                jList1.setSelectedIndex(2);
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage().toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PreparedStatement stat;
        String hobi = "";
        Connection con = null;
        try {
            con = koneksi.getConnection();
            String SqlUpdate = "Update Data_Siswa set Alamat =?, Hobi = ?, Jurusan = ?, Asal_Sekolah = ? where No_Induk=?";
            stat = con.prepareStatement(SqlUpdate);
            String No_Induk = jTextField2.getText();
            String Alamat = jTextArea1.getText();
            if (jCheckBox1.isSelected()) {
                hobi = jCheckBox1.getText();
            }
            if (jCheckBox2.isSelected()) {
                hobi = jCheckBox2.getText();
            }
            if (jCheckBox2.isSelected() && jCheckBox1.isSelected()) {
                hobi = jCheckBox1.getText() + " " + jCheckBox2.getText();
            }
            String jurusan = jComboBox1.getSelectedItem().toString();
            String Asal_Sekolah = jList1.getSelectedValue().toString();
            stat.setString(1, Alamat);
            stat.setString(2, hobi);
            stat.setString(3, jurusan);
            stat.setString(4, Asal_Sekolah);
            stat.setString(5, No_Induk);
            int i = stat.executeUpdate();
            if (i != 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage().toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con = null;
        PreparedStatement stat;
        try {
            con = koneksi.getConnection();
            String SqlUpdate = "delete data_siswa where No_Induk =?";
            stat = con.prepareStatement(SqlUpdate);
            String No_Induk = jTextField2.getText();
            stat.setString(1, No_Induk);
            int i = stat.executeUpdate();
            if (i != 0) 
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage().toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connection con = null;
        CallableStatement stat;
        String jenis_kelamin = "";
        String hobi = "";
        try {
            con = koneksi.getConnection();
            stat = con.prepareCall("{call insertDataSiswa (?,?,?,?,?,?)}");
            String Nama = jTextField1.getText();
            String Alamat = jTextArea1.getText();
            if (jRadioButton1.isSelected()) 
            {
                jenis_kelamin = "Laki-laki";
            }
            if (jRadioButton2.isSelected()) 
            {
                jenis_kelamin = "Perempuan";
            }
            if (jCheckBox1.isSelected()) 
            {
                hobi = jCheckBox1.getText();
            }
            if (jCheckBox2.isSelected()) 
            {
                hobi = jCheckBox2.getText();
            }
            if (jCheckBox2.isSelected() && jCheckBox1.isSelected()) 
            {
                hobi = jCheckBox1.getText() + " " + jCheckBox2.getText();
            }
            String jurusan = jComboBox1.getSelectedItem().toString();
            String Asal_Sekolah = jList1.getSelectedValue().toString();                    
            stat.setString(1, Nama);
            stat.setString(2, Alamat);
            stat.setString(3, jenis_kelamin);
            stat.setString(4, hobi);
            stat.setString(5, jurusan);
            stat.setString(6, Asal_Sekolah);
            int i = stat.executeUpdate();
            if (i != 0) 
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String jenis_kelamin = "";
        String hobi = "";
        String No_Induk = jTextField2.getText();
        String Nama = jTextField1.getText();
        String Alamat = jTextArea1.getText();
        if (jRadioButton1.isSelected()) 
        {
            jenis_kelamin = "Laki-laki";
        }
        if (jRadioButton2.isSelected()) 
        {
            jenis_kelamin = "Perempuan";
        }
        if (jCheckBox1.isSelected()) 
        {
            hobi = jCheckBox1.getText();
        }
        if (jCheckBox2.isSelected()) 
        {
            hobi = jCheckBox2.getText();
        }
        if (jCheckBox2.isSelected() && jCheckBox1.isSelected()) 
        {
            hobi = jCheckBox1.getText() + " " + jCheckBox2.getText();
        }
        String jurusan = jComboBox1.getSelectedItem().toString();
        String Asal_Sekolah = jList1.getSelectedValue().toString();
        JOptionPane.showMessageDialog(null, "NO INDUK= " + No_Induk + " Nama "
                + Nama + " Alamat= " + Alamat + " Jenis Kelamin "
                + jenis_kelamin + " Hobi =" + hobi + " Jurusan = " + jurusan + " Asal Sekolah = "
                + Asal_Sekolah);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        CallableStatement stat;
        ResultSet rs;
        try {
            con = koneksi.getConnection();
            stat = con.prepareCall("{call CariSiswa(?)}");
            String Alamat = jTextArea1.getText().trim();
            stat.setString(1, Alamat);
            rs = stat.executeQuery();
            rs.next();
            jTextField1.setText(rs.getString("Nama").trim());
            jTextArea1.setText(rs.getString("Alamat").trim());
            if (rs.next() == true) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
